select 
  uo.user_uuid,
  uo.user_first_name,
  uo.user_last_name,
  uo.user_email,
  uo.user_phone_number,
  uo.user_creation_date,
  uo.user_last_update_date,
  uo.order_uuid,
  uo.order_date,
  uo.user_address||', '||uo.user_zipcode||', '||uo.user_state||', '||uo.user_country as order_delivery_address,
  uo.order_status, 
  uo.order_expected_delivery_date,
  uo.order_tracking_id,
  uo.order_shipping_service,
  uo.order_delivery_date,
  extract(day from uo.order_delivery_date-uo.order_date) as orders_days_to_deliver,
  uo.order_total as order_total_cost_paid_by_client,
  uo.order_total-uo.order_shipping_cost as order_product_cost_paid_by_client,
  uo.order_shipping_cost as order_shippping_cost_paid_by_client,
  uo.order_total-uo.order_shipping_cost as order_greenery_revenue,
  uo.order_cost as order_greenery_cost,
  uo.order_total-uo.order_shipping_cost-uo.order_cost as order_greenery_margin,
  uo.order_product_types,
  uo.order_quantity_of_products      
from {{ ref('int_user_orders_metrics') }} uo